### ISSUE TITLE
font size at terminal window

### ISSUE THREAD

**Issue by ysupr** [jesusOmar/one-dark-phpstorm#9]
Hi, thanks for your theme, it's look good on mine. 

the only issue i see are the font size at terminal window, it's too big and didn;t follow font size preference i did. 

![screen shot 2016-09-18 at 12 29 15 pm](https://cloud.githubusercontent.com/assets/1949957/18612900/c30446fa-7d9b-11e6-907f-ba4af1775f87.png)

left (text editor) are right font size from preferences, but right side (terminal window) are too big.

**Comment by jesusOmar** [comment]
@ysupr Since my theme is set to use the font at size 16, the terminal is also set at 16, if you modify the font size on the editor, you would also need to change the terminal aka "console font" size as well. Look for this setting inside Editor -> Colors & Fonts -> Console Font.

<img width="1040" alt="preferences_and_version20161006141451_php_-_eip_stanford_edu_-____code_eip_stanford_edu_" src="https://cloud.githubusercontent.com/assets/377084/19157614/e50c087a-8bb3-11e6-9f74-e2601e59a616.png">

**Comment by ysupr** [comment]
Ah, i really didn't know there is settings for 'console font', 

thank you so much
